### ISSUE TITLE
Adding db user fails on EC2

### ISSUE THREAD

**Issue by tklo** [chef-cookbooks/database#127]
Hi, I wrote following cookbook recipe modifying pg_hba and creating a database user and a database.

node.default['postgresql']['pg_hba'] = [
    {:comment => '# TYPE  DATABASE        USER            IP-ADDRESS             METHOD',
    :type => 'local', :db => 'all', :user => 'all', :addr => nil, :method => 'trust'},
    # local koji apache trust
    {:comment => '# TYPE  DATABASE        USER            IP-ADDRESS             METHOD',
    :type => 'local', :db => 'apache', :user => 'apache', :addr => nil, :method => 'trust'},
    # local koji koji trust
    {:comment => '# TYPE  DATABASE        USER            IP-ADDRESS             METHOD',
    :type => 'local', :db => 'apache', :user => 'apache', :addr => nil, :method => 'trust'},
    # host koji koji 127.0.0.1/32 trust
    {:comment => '# TYPE  DATABASE        USER            IP-ADDRESS             METHOD',
    :type => 'host', :db => 'apache', :user => 'all', :addr => '127.0.0.1/32', :method => 'trust'}, 
    # host all all 127.0.0.1/32 ident
    {:comment => '# TYPE  DATABASE        USER            IP-ADDRESS             METHOD',
    :type => 'host', :db => 'template1', :user => 'all', :addr => '127.0.0.1/32', :method => 'trust'}
]

include_recipe 'build-essential::default'
include_recipe "postgresql::server"
include_recipe "postgresql::client"
include_recipe "database::postgresql"

connection_user_postgres = {
  :host     => '127.0.0.1',
  :port     => node['postgresql']['config']['port'],
  :username => 'postgres',
  :password => node['postgresql']['password']['postgres']
}

postgresql_database_user "apache" do
    connection connection_user_postgres
    # provider   Chef::Provider::Database::PostgresqlUser
    password   'apache'
    action     :create
    database_name 'apache'
end

database "apache" do
    connection connection_user_postgres
    provider   Chef::Provider::Database::Postgresql
    template 'DEFAULT'
    encoding 'DEFAULT'
    tablespace 'DEFAULT'
    connection_limit '-1'
    owner 'apache'
    action     :create
end

When I lunch it using Vagrant on Amazon EC2 (using vagrant-aws) it results in following error:

==> koji:     - execute "bash"  "/tmp/chef-script20150205-3245-sv5qda"                                                                [149/9459]
==> koji: Recipe: postgresql::ruby
==> koji:   \* chef_gem[pg] action install (up to date)
==> koji: Recipe: koji::database
==> koji:   \* postgresql_database_user[apache] action create
==> koji:  
==> koji:     ================================================================================
==> koji:     Error executing action `create` on resource 'postgresql_database_user[apache]'
==> koji:     ================================================================================
==> koji:  
==> koji:     PG::SyntaxError
==> koji:     ---------------
==> koji:     ERROR:  syntax error at or near "NOREPLICATION"
==> koji:     LINE 1: ...  PASSWORD 'apache' NOCREATEDB NOCREATEROLE LOGIN NOREPLICAT...
==> koji:                                                                  ^
==> koji:  
==> koji:     Cookbook Trace:
==> koji:     ---------------
==> koji:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql_user.rb:53:in `exec'
==> koji:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql_user.rb:53:in`action_create'
==> koji:  
==> koji:     Resource Declaration:
==> koji:     ---------------------
==> koji:     # In /var/chef/cache/cookbooks/koji/recipes/database.rb
==> koji:  
==> koji:      80: postgresql_database_user "apache" do
==> koji:      81:      connection connection_user_postgres
==> koji:      82:      # provider   Chef::Provider::Database::PostgresqlUser
==> koji:      83:      password   'apache'
==> koji:      84:      action     :create
==> koji:      85:      database_name 'apache'
==> koji:      86: end
==> koji:      87: 
==> koji:  
==> koji:     Compiled Resource:
==> koji:     ------------------
==> koji:     # Declared in /var/chef/cache/cookbooks/koji/recipes/database.rb:80:in `from_file'
==> koji:                                                                                                                             [112/9459]
==> koji:     postgresql_database_user("apache") do
==> koji:       provider Chef::Provider::Database::PostgresqlUser
==> koji:       action [:create]
==> koji:       retries 0
==> koji:       retry_delay 2
==> koji:       default_guard_interpreter :default
==> koji:       database_name "apache"
==> koji:       username "apache"
==> koji:       host "localhost"
==> koji:       privileges [:all]
==> koji:       login true
==> koji:       declared_type :postgresql_database_user
==> koji:       cookbook_name "koji"
==> koji:       recipe_name "database"
==> koji:       connection {:host=>"127.0.0.1", :port=>5432, :username=>"postgres", :password=>"123123"}
==> koji:       password "apache"
==> koji:     end
==> koji:  
==> koji: [2015-02-05T12:43:53+00:00] INFO: Running queued delayed notifications before re-raising exception
==> koji: [2015-02-05T12:43:53+00:00] INFO: template[/etc/sysconfig/pgsql/postgresql] sending restart action to service[postgresql](delayed)
==> koji:   \* service[postgresql] action restart[2015-02-05T12:43:56+00:00] INFO: service[postgresql] restarted
==> koji: 
==> koji:     - restart service service[postgresql]
==> koji: 
==> koji: Running handlers:
==> koji: [2015-02-05T12:43:56+00:00] ERROR: Running exception handlers
==> koji: Running handlers complete
==> koji: [2015-02-05T12:43:56+00:00] ERROR: Exception handlers complete
==> koji: [2015-02-05T12:43:56+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> koji: Chef Client failed. 72 resources updated in 292.750859529 seconds
==> koji: [2015-02-05T12:43:56+00:00] INFO: Sending resource update report (run-id: 47de9805-1cdb-4bc4-83b7-3e3fbbd1344a)
==> koji: [2015-02-05T12:43:57+00:00] ERROR: postgresql_database_user[apache](koji::database line 80) had an error: PG::SyntaxError: ERROR:  sy
ntax error at or near "NOREPLICATION"
==> koji: LINE 1: ...  PASSWORD 'apache' NOCREATEDB NOCREATEROLE LOGIN NOREPLICAT...
==> koji:                                                              ^
==> koji: 
==> koji: [2015-02-05T12:43:57+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR warden: Error occurred: Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

(Rest of the trace: http://pastebin.com/xCd8Q4fK )

Is it a bug in database cookbook or rather something in my configuration or maybe it is a problem in Vagrant? Any ideas? Thanks in advance...

**Comment by tklo** [comment]
What's interesting the error is a little bit different when I use alternative notation of creating a database user:

database_user "apache" do
	connection connection_user_postgres
	provider   Chef::Provider::Database::PostgresqlUser
	password   'apache'
	action     :create
	database_name 'apache'
end



In such situation the error is:

==> koji: Recipe: koji::database
==> koji:   * database_user[apache] action create
==> koji:     
==> koji:     ================================================================================
==> koji:     Error executing action `create` on resource 'database_user[apache]'
==> koji:     ================================================================================
==> koji:     
==> koji:     NoMethodError
==> koji:     -------------
==> koji:     undefined method `createdb' for Chef::Resource::DatabaseUser
==> koji:     
==> koji:     Cookbook Trace:
==> koji:     ---------------
==> koji:     /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql_user.rb:42:in `action_create'


(Full trace here: http://pastebin.com/5MmHyHs0 )

**Comment by tklo** [comment]
If anybody would like to replicate the error, here is my Vagrantfile:
http://pastebin.com/C0gfWyrE

**Comment by tklo** [comment]
Ok, now I know where is the problem. It seems that postgresql cookbook installs version 8.4 on CentOS 6.5 and database cookbook tries to create role using keywords (NOREPLICATION) from 9.1. I have to either switch to version 9.1 using postgresql cookbook or get rid of of "NOREPLICATION" in database cookbook.

**Comment by tklo** [comment]
My workaround of the problem is to simply execute "createuser" as postgres system user:

execute "Create a postgresql user for koji but grant no privileges" do
	user "postgres"
	exists = <<-EOH
		psql -c '\du' | grep -c apache  # don't do it, if the user exists 
	EOH
	command "createuser --no-createdb --login --no-createrole --no-superuser apache"
	not_if exists, :user => "postgres"
end

**Comment by dtsosie** [comment]
I had this same problem when installing with a Jira cookbook. If you add my patch, no work arounds will be required as I detect the issue prior to executing the syntax error.

**Comment by cheeseplus** [comment]
Closing this as the fix in #132 was merged.
