### ISSUE TITLE
Please add updated_by_last_action to actions

### ISSUE THREAD

**Issue by joerg** [chef-cookbooks/database#135]
I have a stupid java service which needs to be notified on a database change which I do which mysql_database's action :query. This is currently not possible, because the updated_by_last_action is missing. So please add

``` ruby
action :<any action> do
  <some code>
  new_resource.updated_by_last_action true
end
```

to all actions so this works:

``` ruby
mysql_database 'MySQL: Set something' do
  connection database_connection
  database_name 'my_db_name'
  sql "UPDATE x SET y=z WHERE a=b"
  action :query
  not_if { <some custom guard i wrote> }
  notifies :restart, 'service[stupid_java_thingie]'
end
```

**Comment by kisoku** [comment]
Blindly setting new_resource.updated_by_last_action to true will case you java service to restart even in the case where your custom guard evaluates to true.

 In any case, I will try to work on a diff for this soon

**Comment by joerg** [comment]
Sorry, but this does not seem to be true. I currently have 'new_resource.updated_by_last_action true' in the :query action and my service does not get restarted each time.

```bash
  * mysql_database[MySQL: Update ID] action query (skipped due to not_if)
  * mysql_database[MySQL: Add recovery admin] action query (skipped due to only_if)
  * mysql_database[MySQL: Set recovery admin password] action query (skipped due to not_if)
....
```

And there is no service restart later on.
Btw: I wrote a custom guard which queries the MySQL database so I can check if the database needs a change at all. This would be a cool new feature to have built in.

**Comment by kisoku** [comment]
Well by all means please make a Pull Request and show us your code, I would be more than happy to test it and discuss it with @someara for potential inclusion.

**Comment by joerg** [comment]
Well, there isn't much for a pull request since I moved the module to a different cookbook. I first didn't want to touch the database cookbook at all but since the updated_by_last_action was missing I had to. But here is what I did:
```ruby
module Common
  module MysqlQueryGuard
    require 'mysql2'
    def mysql_query(query_string, connection)
      c = Mysql2::Client.new( connection )
      out = c.query(query_string)
      c.close

      out
    end

    # If query is a single value get that one.
    # A mysql2 result only has each to get the values...
    def mysql_query_value(query_string, connection)
      out = ''
      mysql_query(query_string, connection).each do |i|
        out = i.values
      end
      out[0]
    end
  end
end

Chef::Resource::MysqlDatabase.send(:include, Common::MysqlQueryGuard)
```
This adds two functions to be used in not_if and only_if. Basically they are copies of what is already present in the cookbook but in private space. I added the updated_by_last_action as stated above and I had to add this fix: https://github.com/opscode-cookbooks/database/pull/129.
With these changes something like this is possible:
```ruby
mysql_database 'MySQL: Set recovery admin password' do
  connection database_connection
  database_name settings['database']['name']
  sql "UPDATE user_table SET password='#{password_hash}' where user_name='recovery-admin'"
  action :query
  not_if { mysql_query_value('SELECT password FROM user_table WHERE name=\'recovery-admin\';', database_connection).include?(password_hash) }
  notifies :restart, 'service[stupid_java_daemon]'
end
```
This is just a stupid example but it will update the password if it is not correct and restart the service in this case. If you are interested I could work this out and send you a pull request, but this will need some structural changes since currently all worker functions are private.

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
