### ISSUE TITLE
cannot load such file -- mysql2

### ISSUE THREAD

**Issue by ikozel** [chef-cookbooks/database#141]
I'm using:
cookbook "database", "4.0.3"
and have installed gem:  mysql2 (0.3.18) 
also depend on: cookbook 'mysql2_chef_gem'
also installed: mysql-5.6.23 

Any idea what is missing? 

But still getting this error: 

 mysql_database[flite_igor] action create
 ================================================================================
           Error executing action `create` on resource 'mysql_database[flite_igor]'
           ================================================================================

```
       LoadError
       ---------
       cannot load such file -- mysql2

       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb:103:in `test_client'
       /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb:37:in `block in <class:Mysql>'
```

**Comment by someara** [comment]
You need to put a mysql2_chef_gem resource in a recipe somewhere before using a mysql_database resource



—

**Comment by ikozel** [comment]
something like this?

include_recipe "mysql2_chef_gem"
mysql_connection_info = {  :host     => 'localhost',  :username => 'mysql',  :password => 'ssss'} 

     On Saturday, March 7, 2015 11:47 AM, Sean OMeara <notifications@github.com> wrote:
   

 You need to put a mysql2_chef_gem resource in a recipe somewhere before using a mysql_database resource



—

**Comment by someara** [comment]
Like this:

https://gist.github.com/someara/ae50488f472d8e2f1352

-s

**Comment by ikozel** [comment]
Did that and got another error: superclass mismatch for class MysqlChefGem

       superclass mismatch for class MysqlChefGem              Cookbook Trace:       ---------------         /tmp/kitchen/cache/cookbooks/percona/libraries/provider_mysql_chef_gem.rb:10:in `<class:Provider>'         /tmp/kitchen/cache/cookbooks/percona/libraries/provider_mysql_chef_gem.rb:2:in `<class:Chef>'         /tmp/kitchen/cache/cookbooks/percona/libraries/provider_mysql_chef_gem.rb:1:in `<top (required)>'              Relevant File Content:       ----------------------       /tmp/kitchen/cache/cookbooks/percona/libraries/provider_mysql_chef_gem.rb:                3:      # rubocop:disable LineLength         4:      #         5:      # Public:         6:      # Monkey patch to not install mysql client dev libraries over ours         7:      # https://github.com/opscode-cookbooks/mysql/blob/master/libraries/provider_mysql_client_ubuntu.rb         8:      #         9:      # rubocop:enable LineLength        10>>     class MysqlChefGem < Chef::Provider::LWRPBase        11:        def action_install        12:          converge_by "install mysql chef_gem and dependencies" do        13:            recipe_eval do        14:              run_context.include_recipe "build-essential::default"        15:              run_context.include_recipe "percona::client"        16:            end        17:          18:            chef_gem "mysql" do        19:              action :install               

     On Saturday, March 7, 2015 12:55 PM, Sean OMeara <notifications@github.com> wrote:
   

 Like this:

https://gist.github.com/someara/ae50488f472d8e2f1352

-s

**Comment by someara** [comment]
Can you paste that into a GitHub gist so it's readable?



—

**Comment by ikozel** [comment]
sure, just.
gist:ae50488f472d8e2f1352

|   |
|   |   |   |   |   |
| gist:ae50488f472d8e2f1352connection_info = { host: '127.0.0.1', username: 'root', password: 'ub3rs3kur3' }   mysql_service 'default' do port '3306' version '5.5' initial_root_password 'change me' action [:create, :start] end  |
|  |
| View on gist.github.com | Preview by Yahoo |
|  |
|   |

   

     On Saturday, March 7, 2015 5:22 PM, Sean OMeara <notifications@github.com> wrote:
   

 Can you paste that into a GitHub gist so it's readable?



—

**Comment by someara** [comment]
Looks like it's a problem with the Percona cookbook you're using. It shouldn't be shipping those mysql_chef_gem classes under libraries. 






-s





—

**Comment by ikozel** [comment]
Can I use mysql cookbook to install Percona server? 
Igor 
 

     On Saturday, March 7, 2015 5:30 PM, Sean OMeara <notifications@github.com> wrote:
   

 Looks like it's a problem with the Percona cookbook you're using. It shouldn't be shipping those mysql_chef_gem classes under libraries. 






-s





—

**Comment by someara** [comment]
Nope. The cookbook is scoped to the Oracle mysql-community-server only

-s



—

**Comment by ikozel** [comment]
agh.. thanks Sean. btw, we've worked together on the project @ Lookout last year summer. 
Igor 

     On Saturday, March 7, 2015 5:36 PM, Sean OMeara <notifications@github.com> wrote:
   

 Nope. The cookbook is scoped to the Oracle mysql-community-server only

-s



—

**Comment by ikozel** [comment]
What would you suggest in this situation?
Igor  

     On Saturday, March 7, 2015 5:43 PM, igor kozel <igor_kozel@yahoo.com> wrote:
   

 agh.. thanks Sean. btw, we've worked together on the project @ Lookout last year summer. 
Igor 

     On Saturday, March 7, 2015 5:36 PM, Sean OMeara <notifications@github.com> wrote:
   

 Nope. The cookbook is scoped to the Oracle mysql-community-server only

-s



—

**Comment by someara** [comment]
Fork and patch, or roll your own.




There is a yum-percona cookbook on Supermarket to help handle the repositories






—

**Comment by asciifaceman** [comment]
I resolved this on mine by changing the order of operations:

Chef::Log.info("installing the mysql2 chef gem")
mysql2_chef_gem 'default' do
  provider Chef::Provider::Mysql2ChefGem::Percona
end

Chef::Log.info("Begin calling percona cookbook.")
include_recipe "percona::server"

**Comment by ashwinrayaprolu1984** [comment]
I get the same error for Oracle Mysql Community server
https://gist.github.com/ashwinrayaprolu1984/1e26584ae3a1696b3ba20ca20f1924bd

Not sure where i'm wrong.

[ashwin@localhost myface]$ berks -v
4.3.5
[ashwin@localhost myface]$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
[ashwin@localhost myface]$ vagrant -v
Vagrant 1.8.5

**Comment by abhishekdoshi** [comment]
Finally I resolve that issue after several research..you can please do such as below
1) Add repo file of mysql-community using (include_recipe "yum_mysql_community::mysql55) 
2) install mysql2_chef_gem
3)Database details 

successfully it's works, If you still have any problem, please ping me

**Comment by tas50** [comment]
Closing this out since the solution is in the comments above
