### ISSUE TITLE
running psql commands in a postgres query

### ISSUE THREAD

**Issue by pmoosh** [chef-cookbooks/database#143]
Probably something I do wrong, but here is my code:
query = "\i #{node['postgres']['testfile']}"

postgresql_database 'load database' do
  connection(
    :host      => '127.0.0.1',
    :port      => 5432,
    :username  => node['postgres']['user'],
    :password  => node['postgresql']['password']['postgres']
  )
  database_name node['postgres']['dbname']
  sql query
  action :query
end

This results in the following error:

==> default: postgresql_database("load database") do
==> default:   provider Chef::Provider::Database::Postgresql
==> default: 
==> default:   action [:query]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   database_name "test"
==> default:   declared_type :postgresql_database
==> default: 
==> default:   cookbook_name :"test-postgres"
==> default:   recipe_name "default"
==> default:   connection {:host=>"127.0.0.1", :port=>5432, :username=>"test", :password=>"test"}
==> default:   sql "i /vagrant/test/integration/default/short.ddl"
==> default: end

with the backslash missing,
If I do 2 backslashes result is sql "\i /vagrant/test/integration/default/short.ddl"

**Comment by delta440** [comment]
I'm having the same problem, did you ever find a solution?

**Comment by cheeseplus** [comment]
This should be done by adapting the following from the example (replacing postgres as appropriate.)

```
# Query a database from a sql script on disk
mysql_database 'run script' do
  connection mysql_connection_info
  sql { ::File.open('/path/to/sql_script.sql').read }
  action :query
end
```

If that doesn't work please feel free to open a new issue.
