### ISSUE TITLE
mysql_database_user should not add quotes around database_name of '*'

### ISSUE THREAD

**Issue by acoulton** [chef-cookbooks/database#146]
Given the following resource definition:

``` ruby
mysql_database_user username do
  action        :grant
  connection    root_connection
  database_name '*'
  host          'localhost'
  password      pwd
  privileges    ['SELECT']
end
```

The mysql_database_user provider should grant global privileges by running:

```
GRANT SELECT ON *.* TO....
```

Instead, it quotes the `*` database name producing the query:

```
GRANT SELECT ON `*`.* TO...
```

which only grants permissions on a database named `*`.

This appears to be an unexpected regression introduced in 03477570b420b13c17278d690ea3d83a0107f872 which added support for the require SSL option. The diff includes this change:

```
- grant_statement = "GRANT #{@new_resource.privileges.join(', ')} ON #{@new_resource.database_name && @new_resource.database_name != '*' ? "`#{@new_resource.database_name}`" : '*'}.#{@new_resource.table && @new_resource.table != '*' ? "`#{@new_resource.table}`" : '*'} TO `#{@new_resource.username}`@`#{@new_resource.host}` IDENTIFIED BY "
+ grant_statement = "GRANT #{@new_resource.privileges.join(', ')} ON #{@new_resource.database_name ? "`#{@new_resource.database_name}`" : '*'}.#{@new_resource.table ? "`#{@new_resource.table}`" : '*'} TO `#{@new_resource.username}`@`#{@new_resource.host}` IDENTIFIED BY "
```

The new logic always quotes the database name, where the old logic only quoted if it was != *. This change is not mentioned in the commit message or in #62.

The provider has since been refactored but the [changed logic has been retained](https://github.com/opscode-cookbooks/database/blob/master/libraries/provider_database_mysql_user.rb#L95)

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
