### ISSUE TITLE
mysql_database with action :query cannot execute several sql statements

### ISSUE THREAD

**Issue by multiservicio** [chef-cookbooks/database#151]
Let's assume we have: 

```
mysql_database 'default' do
  database_name 'default'
  connection mysql_connection_info
  sql <<-EOH
CREATE TABLE IF NOT EXISTS table1 (
  client_id VARCHAR(80) NOT NULL,
);
CREATE TABLE IF NOT EXISTS table2 (
  client_id VARCHAR(80) NOT NULL,
);
CREATE TABLE IF NOT EXISTS table3 (
  client_id VARCHAR(80) NOT NULL,
);
EOH
  action :query
end
```

And as MySQL2 gem: 

```
mysql2_chef_gem 'default' do
  gem_version '0.3.17'
  action :install
end
```

When running chef-client we get and error similar to this:

```
ERROR: mysql_database[default] (my cookbook::bootstrap_db line xx) had an error: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS table2 (
 client_id VARCHAR(80) NOT NULL,' at line xx
```

Table2 is the hint. 

After some debugging we found that the "guilty" is the MySql2 gem that cannot execute several sql statements unless you specify:

```
Mysql2::Client.default_query_options[:connect_flags] |= Mysql2::Client::MULTI_STATEMENTS
```

as read in:  http://stackoverflow.com/questions/4856759/how-to-run-multiple-sql-queries-through-one-call-in-mysql2-gem-in-irb

for example in a ruby block:

```
ruby_block "modifying MySQL2 client" do
  block do
    Mysql2::Client.default_query_options[:connect_flags] |= Mysql2::Client::MULTI_STATEMENTS
  end
  action :run
end
```

After adding that, chef-client completes without any complain. 

After looking at the provider I think the query options must be somewhere near here:
database/libraries/provider_database_mysql.rb :138

```
def test_client
  require 'mysql2'
  @test_client ||=
      Mysql2::Client.new(
          host: new_resource.connection[:host],
          socket: new_resource.connection[:socket],
          username: new_resource.connection[:username],
          password: new_resource.connection[:password],
          port: new_resource.connection[:port]
      )
end
```

I never made a pull request so I wanted to share this before doing it.

Where it should be the best place to specify it? or if this was left out on purpose by design and instead we should use different approach. 

Thanks,

**Comment by someara** [comment]
Hi.

This is definitely an oversight, rather than a "feature'.
Send a PR! Thanks!

-s

**Comment by joerg** [comment]
@fonzai: I have done pretty much the same to get this working, but I also had to add this:
```ruby
action :query do
  begin
-   query_sql = new_resource.sql                                                        
+   query_sql = new_resource.sql_query                                                  
    Chef::Log.debug("Performing query [#{query_sql}]")
    query_client.query(query_sql)
+   while query_client.next_result                                                      
+     query_client.store_result                                                         
+   end
  ensure
```

**Comment by webbower** [comment]
Holy crap! I'm not crazy! Someone else ran into this problem too AND identified it. So +1 to this problem, although I dropped in @multiservicio's `ruby_block` statement above AFTER the block to install the `mysql2_chef_gem` and it fails for me with the following error:

```
NameError
---------
uninitialized constant Chef::Recipe::Mysql2
```

However, I was running into this problem with trying to load a dump file into MySQL and the workaround was using an `execute` block to generate a `mysql` command for CLI:

```
execute 'restore-databases' do
  command "mysql -h #{node['app']['mysql']['host']} -u #{node['app']['mysql']['db']['user']} -p#{node['app']['mysql']['db']['pass']} -D #{node['app']['mysql']['db']['name']} < /vagrant/#{node['app']['mysql']['db']['dump']}"
end
```

**Comment by fonzai** [comment]
@webbower Could you try the pull request that was made by @razor-x https://github.com/opscode-cookbooks/database/issues/154 and let us know if it works for you too? That would be helpful :).

**Comment by webbower** [comment]
@fonzai I pulled down the PR and referencing the local cookbook in my Berksfile (`==> default: Using database (4.0.6) from source at ../database_patch`). The error stopped, but now it seems to be completely ignoring the SQL dump file. When I `vagrant ssh` into the VM and log into the MySQL client, the database is created as directed in the earlier database creation instruction, but the DB is empty. `show tables;` gives me an empty set.

```ruby
mysql_database node['app']['mysql']['db']['name'] do
  connection    app_db_connection_info
  database_name node['app']['mysql']['db']['name']
  sql           { ::File.open("/vagrant/#{node['app']['mysql']['db']['dump']}").read }
  action        :query
end
```

**Comment by isuftin** [comment]
Is there a fix for this? I am also seeing the `Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near...` issue.

I did drop in 

```
ruby_block "modifying MySQL2 client" do
  block do
    Mysql2::Client.default_query_options[:connect_flags] |= Mysql2::Client::MULTI_STATEMENTS
  end
  action :run
end
```

... but like @webbower I am also seeing the `uninitialized constant Chef::Recipe::Mysql2` issue. This is happening with the latest version of the database cookbook.

**Comment by fonzai** [comment]
@isuftin Bummer, I had totally forgotten this for a long while. I'll try to find time with @multiservicio to check how it worked.

**Comment by danielBingham** [comment]
This still seems to be an issue with the latest version of the database cookbook.  I ran the following:

```ruby
schema_path = File.join(node['my_app']['database']['data_directory'], node['my_app']['database']['schema_file'])

mysql_database node['my_app']['database']['name'] do
    connection connection_info
    sql { ::File.open(schema_path).read }
    action :query
end
```

And I got the following error:

```
==> default: ================================================================================
==> default:     
==> default: Error executing action `query` on resource 'mysql_database[my_app]'
==> default:     
==> default: ================================================================================   
==> default: Mysql2::Error
==> default: 
==> default:     -------------
==> default:     You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `habits` (`symbol`, `name`, `description`) 
==> default:             VALUES ('E', 'Ev' at line 10
```

The insert statement is the second line of the referenced schema file.  I'm using database cookbook version 5.1.2 in the context of provision an Ubuntu 14.04 virtualbox vm through vagrant.

After the error, I logged into the server and ran the import manually using a call to ``mysql database_name < schema_file.sql`` just to confirm it wasn't an error in my SQL file.

**Comment by catalincatana** [comment]
Hi, 

I am facing the same error for one of my scripts. If I run the contents of the script file line by line, it works, but if i'm placing the script path like:

mysql_database 'test' do
    connection connection_info
    sql { ::File.open('/tmp/test_path.sql').read }
    action :query
end

It throws me the error:
Mysql2::Error
           -------------
           You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use
near 'SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
           SET @OL' at line 4

If i'll go and run manually the script with mysql -u user -ppassword < /tmp/test_path.sql it works. (No SQL syntax error)

Did anyone find any solution for this?

Thanks

**Comment by hedgehog** [comment]
**NOTE: There is a limit to the length of a single line you can feed the MySQL gem/server .**

Having said that....

In case you are following at home... in a Chef context the least offensive workaround is something like this:
````ruby
  # Query database from a multi-line sql script on disk
  pth = '/tmp/multiline_file.sql'
  ln = ::File.readlines(pth).join('')
  database "run multiline SQL script" do
    connection mysql_connection_info
    provider   node['my']['cookbook']['provider']
    sql ln
    database_name 'mysql'
    action :query
  end
````

This might explain why no-one (i.e. me) has bothered to fix this?

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
