### ISSUE TITLE
Database and User creation fails for SQL Server on AWS RDS

### ISSUE THREAD

**Issue by ramarnat** [chef-cookbooks/database#158]
Pops up this error:

```
FATAL: TinyTds::Error: sql_server_database[new_db] (C:\chef\cookbooks\lib_epm\providers\silent_xml_file.rb line 77) had an error: TinyTds::Error: SELECT failed because the following SET options have incorrect settings: 'CONCAT_NULL_YIELDS_NULL, ANSI_WARNINGS'. Verify that SET options are correct for use with indexed views and/or indexes on computed columns and/or filtered indexes and/or query notifications and/or XML data type methods and/or spatial index operations.
```

Based on this https://github.com/rails-sqlserver/tiny_tds/blob/40aaf6e09e62e8f943ee3731da1f9abd42650ecc/test/test_helper.rb#L49

I monkey patched the cookbook:

```
require 'chef/provider'

class Chef
  class Provider
    class Database
      class SqlServer < Chef::Provider
        def db
          @db ||= begin
            client = ::TinyTds::Client.new(
              host: @new_resource.connection[:host],
              username: @new_resource.connection[:username],
              password: @new_resource.connection[:password],
              port: @new_resource.connection[:port] || 1433
            )
            client.execute('SET ANSI_DEFAULTS ON').do
            client.execute('SET CURSOR_CLOSE_ON_COMMIT OFF').do
            client.execute('SET IMPLICIT_TRANSACTIONS OFF').do
            client.execute('SET TEXTSIZE 2147483647').do
            client.execute('SET CONCAT_NULL_YIELDS_NULL ON').do
            client            
          end
        end
      end
    end
  end
end
```

If this is feasible to add to the cookbook, I can create a PR

**Comment by Habbie** [comment]
@ramarnat have you ever contacted Amazon about this? I feel they should fix it.

**Comment by ramarnat** [comment]
@Habbie why do you think so? This seems to be a client side issue (i.e. the SET options need to be appropriate for the database features) and seems to be addressed by other libraries by adjusting the SET options.

**Comment by Habbie** [comment]
Sorry for not responding earlier - I fixed this issue for myself by switching from AWS to Azure. But as I recall it, the error is a direct result of AWS setting up MSSQL in a weird way so they can count databases using triggers etc, requiring users to do various settings in their apps that they would not need with any other MSSQL machine.

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
