### ISSUE TITLE
invalid syntax when granting repl_client privilege

### ISSUE THREAD

**Issue by jslusher** [chef-cookbooks/database#163]
I can't figure out what I'm doing wrong, so I'm hoping someone can help me. I have this as a user that I want to add:

```
mysql_database_user 'repmon' do
  connection mysql_connection_info
  password 'password'
  host '%'
  privileges [:super,:event,:trigger,:repl_client]
  action :grant
end
```

I'm getting this when I try to run that:

```
Mysql2::Error
       -------------
       You have an error in your SQL syntax; check the manual that corresponds to your MySQL server    version for the right syntax to use near 'repl_client ON *.* TO 'rep_monitor'@'%' IDENTIFIED BY 'password'' at line 1
```

**Comment by jslusher** [comment]
I was able to get this to work by changing the privileges into an array of strings instead of the symbols. 

      privileges ['super','replication client','event','trigger','create tablespace']

**Comment by geleman** [comment]
I'm getting same error for :repl_slave

**Comment by alexandrezia** [comment]
Same here, issues with :create_tmp_table and   :lock_tables
This doesn't works:
```
privileges [:select,:insert,:update,:delete,:create,:drop,:index,:alter,:create_tmp_table,:lock_tables]
```
But this works:
```
privileges ['select','insert','update','delete','create','drop','index','alter','create temporary tables','lock tables']
```

**Comment by sentience** [comment]
Thanks for the work-around, @alexandrezia!

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
