### ISSUE TITLE
database_user LWRP refuses to change user password only

### ISSUE THREAD

**Issue by BarthV** [chef-cookbooks/database#164]
Ohai,

With a mysql backend I'm just trying to change a user's password but it seems not possible since `:create` and `:grant` actions only tests user presence (https://github.com/opscode-cookbooks/database/blob/master/libraries/provider_database_mysql_user.rb#L159-L165) and don't even try to compare provided password from the current one.

This causes a annoying missunderstanding since the resource is validated during chef-run with the "new" password provided but -in fact- the user never changes in mysql :

```
mysql_database_user[jdoe-localhost] action grant (up to date)
```

**Comment by BarthV** [comment]
Maybe it could be great to implement this "password change" feature into ```:create``` action.
It could be only triggered when a difference with the 2 passwords is detected

**Comment by tas50** [comment]
Closing this as the two PRs address the issue
