### ISSUE TITLE
mysql_database_user grant :repl_client gets syntax error

### ISSUE THREAD

**Issue by krtyyy** [chef-cookbooks/database#171]
Hi all,

We had been using mysql_database :query to do some grant statements, but given the issue we're having with 4.0.9 (Issue 170) we're moving those to mysql_database_user :grant, where they ought to be.

The problem now is that using :repl_client gives me a syntax error back from MySQL.  In order to get things to work, I have to use the string "replication client" instead of :repl_client. (See below.)

The actual error is:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'repl_client ON _._ TO 'failover'@'...

Sure enough, if I go into mysql and try...
"grant repl_client..."
"grant replication_client..."
"grant REPL_CLIENT..."
etc.
... all fail.  But "grant replication client..." works.

Am I doing something silly or is something broken?

```
mysql_database_user 'failover' do
  connection mysql_connection_info
  password failover_password
  host db_host
  privileges [:super, :process, 'replication client']
  action :grant
end
```

**Comment by krtyyy** [comment]
Quick update: Ditto for :repl_slave ->  "replication slave"

**Comment by geleman** [comment]
https://github.com/chef-cookbooks/database/issues/163
use the string for all. i was having the same issue and that fixed it. it does need to be fixed though.
Also granting from command line in mysql client you have to do this way:
'grant replication client on *.* to user@ip'
same goes with replication slave and any other privilege that is more than one word

**Comment by krtyyy** [comment]
Thanks for the update. My apologies for not seeing that there was already an open issue.

**Comment by geleman** [comment]
no worries I was just trying to help because I was having same issue

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
