### ISSUE TITLE
ChefSpec failing due to load error mysql2_gem

### ISSUE THREAD

**Issue by geleman** [chef-cookbooks/database#172]
The cookbook works fine in running in vagrant and now i'm doing some spec testing. I keep getting the error about the mysql2 not loading which I understand  why, but I do have a separate recipe that installs the mysql2_gem. How am I supposed to get it to load on a spec test? I'm not seeing very good guidance for spec testing in the spec folder regarding any of the the resources that this database cookbook is providing. 

Also when stepping into the resource I don't really know what I am supposed to use after expect.to seems it won't be create_user but maybe grant_user?  Is there any where I see some better spec testing samples?

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
