### ISSUE TITLE
Resolve FC023 warnings

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/database#175]
FC023: Prefer conditional attributes: ./libraries/provider_database_mysql.rb:46
FC023: Prefer conditional attributes: ./libraries/provider_database_mysql.rb:77
FC023: Prefer conditional attributes: ./libraries/provider_database_mysql_user.rb:46
FC023: Prefer conditional attributes: ./libraries/provider_database_mysql_user.rb:76
FC023: Prefer conditional attributes: ./libraries/provider_database_mysql_user.rb:122

**Comment by martinb3** [comment]
The first one looks like a false positive of FC023:
```
    unless schema_present
      converge_by "Creating schema '#{new_resource.database_name}'" do
        begin
           repair_sql = "CREATE SCHEMA IF NOT EXISTS `#{new_resource.database_name}`"
           repair_sql += " CHARACTER SET = #{new_resource.encoding}" if new_resource.encoding
           repair_sql += " COLLATE = #{new_resource.collation}" if new_resource.collation
           Chef::Log.debug("#{new_resource.name}: Performing query [#{repair_sql}]")
           repair_client.query(repair_sql)
        ensure
          close_repair_client
        end
      end
    end
```

Seems like FC is parsing it like a resource being declared by the DSL, guarded by a conditional, when it's not a resource declaration at all.

**Comment by tas50** [comment]
@martinb3 Can you report this case as a bug against FC

**Comment by martinb3** [comment]
@tas50 It came in via IRC in #chef, and I directed the reporting user to file a bug here.

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
