### ISSUE TITLE
Updated privileges automatically after changing user's password

### ISSUE THREAD

**Issue by jkulak** [chef-cookbooks/database#181]
Hi, I'm using database ver. 4.0.9.

I have also checked current master if it was fixed after seeing: https://github.com/chef-cookbooks/database/issues/164 (but it was not).

After changing user's password with `mysql_database_user` I'm setting privileges in the same recipe. I was expecting privileges for this user to be updated, but

```
==> default: * mysql_database_user[myuser] action grant
==> default:  (up to date)
```

Causing unwanted

```
ERROR 1045 (28000): Access denied for user 'myuser'@'localhost' (using password: YES)
```

I guess this should work, as I explicitly call

```
  mysql_database_user db['user'] do
    connection    mysql_connection_info
    database_name db['name']
    privileges    [:all]
    action        :grant
  end
```

to update those privileges.

**Comment by tas50** [comment]
This should be fixed in the 5.1 release.
