### ISSUE TITLE
No idempotency on :grant action for postgresql_database_user

### ISSUE THREAD

**Issue by Ginja** [chef-cookbooks/database#182]
The `:grant:` action for postgresql_database_user executes on every single Chef run. Unlike `:create` or `:drop`, there's no exists? check for it. 

https://github.com/chef-cookbooks/database/blob/master/libraries/provider_database_postgresql_user.rb#L70

**Comment by tas50** [comment]
@Ginja The grant logic has been reworked with the 6.1.0 release. I'm going to close this out, but feel free to open it back up if you're still seeing the issue.
