### ISSUE TITLE
Physical/Logical Files on database create

### ISSUE THREAD

**Issue by thxmike** [chef-cookbooks/database#183]
Is there a way to when creating a database to specify the logical and physical files for mssql server database? Looking through the code it does not appear to be.

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
