### ISSUE TITLE
Examples for postgresql connection information are misleading

### ISSUE THREAD

**Issue by matthew-long** [chef-cookbooks/database#184]
The examples for the connection for postgresql are misleading (I'm uncertain about the other databases).
The password in the example is set to the attribute "node['postgresql']['password']['postgres']". This attribute is the plaintext password required for authentication.
However if using a recipe that installs postgresql and subsequently uses a recipe from this cookbook to access the database authentication will not work.

The "node['postgresql']['password']['postgres']" attribute is intended to be the encrypted password in the postgresql cookbook (see https://supermarket.chef.io/cookbooks/postgresql Chef Solo Note).

Either the examples for the connection properties need updating, or the behaviour of the LWRPs needs to be updated to detect MD5 encrypted passwords (easy enough given the md5 prefix) and authenticate appropriately.

**Comment by http-418** [comment]
I've discovered that the `postgresql_database_user` provider shares this problem.  The 'password' attribute is expected to be a postgresql password hash, not the actual password.

The postgresql password hash is an md5 of the password + username, with 'md5' prefixed.  Here is what I have been using:

```ruby

require 'digest'

postgresql_database_user username do
  connection postgresql_connection_info
  # Confusingly, for the postgres provider, the password field is an
  # md5 hash of the password and the user, NOT a plaintext password.
  password 'md5' + Digest::MD5.hexdigest(password + username).to_s
  action :create
end
```

**Comment by gommo** [comment]
Totally agree

**Comment by iennae** [comment]
Does the latest release fix the confusion? Can you clarify where you are seeing the confusion if it doesn't? I want to make sure I understand what the problem documentation is.

**Comment by fiedl** [comment]
Suppose, the `md5` authentication method is requested:

```json
  "postgresql": {
    "pg_hba": [
      {
        "type": "host", 
        "db": "all", 
        "user": "all",
        "addr": "127.0.0.1/24",
        "method": "md5" 
      }
    ]
  },
```

If you then define connection settings like this,

```
postgresql_connection_info = {
  host: 'localhost',
  username: 'postgres',
  password: "..."
}
```

should the above password be cleartext or md5 then?

Furthermore, should `node['postgresql']['password']['postgres']` be cleartext or md5?

**Comment by iennae** [comment]
So is the issue with the postgresql cookbook documentation or this documentation? Thanks for your continued help!

**Comment by fiedl** [comment]
I'm not sure, yet. How about answering my questions first ;)

> should the above password be cleartext or md5 then?
> 
> Furthermore, should `node['postgresql']['password']['postgres']` be cleartext or md5?

Since I'm new to postgres and just migrating from mysql, I don't know the proper way, yet.

**Comment by iennae** [comment]
This cookbook requires postgresql cookbook if you are using postgresql. The documentation in this cookbook is having an individual use whatever they have configured postgresql database password as using the postgresql attribute **node['postgresql']['password']['postgres']**. If you look at the cookbook https://github.com/hw-cookbooks/postgresql which has the documentation on using postgresql attributes :

> That should actually be the "encrypted password" instead of cleartext, so you should generate it as an md5 hash using the PostgreSQL algorithm.
> 
> You could copy the md5-hashed password from an existing postgres database if you have postgres access and want to use the same password:
> select * from pg_shadow where usename='postgres';
> You can run this from any postgres database session to use a new password:
> select 'md5'||md5('iloverandompasswordsbutthiswilldo'||'postgres');
> You can run this from a linux commandline:
> echo -n 'iloverandompasswordsbutthiswilldo''postgres' | openssl md5 | sed -e 's/.* /md5/'

So why the cookbook documentation for postgresql shows the password as being text i.e. "postgres": "iloverandompasswordsbutthiswilldo". 

the statement right after tells you expectation. 

The password should be md5.

**Comment by iennae** [comment]
I'm going to go ahead and close this. Please do reopen if there are any other questions about this.
