### ISSUE TITLE
I'm unsure that tests in test/integration/default are ever used

### ISSUE THREAD

**Issue by roblperry** [chef-cookbooks/database#187]
All the integration tests are in test/integration/default, but none of the test suites in test kitchen have the name default.  So, I think:

* postgresql_spec.rb needs to be moved to test/integration/postgresql/serversspec
* mysql_spec.rb needs to be moved to test/integration/mysql/serverspec
* spec_helper.rb needs to be moved to test/integration/helpers/serverspec 

Can anyone tell my what that should not be so?

Thanks

**Comment by tas50** [comment]
These should get moved into dirs for each test suite

**Comment by roblperry** [comment]
Hey tas50,

The reason I have not done a pull request for my little change is that testing for centers 7.1 is broken when running against the postgresql 4.0 cookbook, which was released 3 days ago.  However, the existing tests also fail for the same reason.

Set the version dependency to "~> 3.0"  ?
Wait for 4.0 to get fixed?
Can we merge in something that does not pass CI cleanly considering it will be no more broken than the existing code that will not pass CI cleanly?

Thoughts?

**Comment by roblperry** [comment]
This got fixed with https://github.com/chef-cookbooks/database/pull/189.
