### ISSUE TITLE
Possible to use the resources for mysql 5.5

### ISSUE THREAD

**Issue by DrunkenAngel** [chef-cookbooks/database#194]
Hi all , 

just a quick question I am attempting to configure mysql 5.5 via chef and would like to make use of the functions to create databases and tables ect , so I have attempted to add the dependency to 5.5 to my metadata.rb file ( adding 6.0 just bombs due to conflicts) and it does not  exist. is there anyway to make use of the cookbook for mysql 5.5 ?

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
