### ISSUE TITLE
mysql_database_user action :grant -> undefined method `empty?' for Mysql2::Result

### ISSUE THREAD

**Issue by giorgian** [chef-cookbooks/database#198]
I'm trying to use the wordpress cookbook, which includes (on `database` recipe):

    mysql_database_user db['user'] do
      connection    mysql_connection_info
      database_name db['name']
      privileges    [:all]
      action        :grant
    end

This fails:

           NoMethodError
           -------------
           undefined method `empty?' for #<Mysql2::Result:0x0000000d998998>

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/database/libraries/provider_database_mysql_user.rb:108:in `block in <class:MysqlUser>'

I'm using (chef-solo, vagrant):

* database (5.0.0)
* mysql (6.1.3)
* mysql2_chef_gem (1.0.2)

Please tell me if I need to include more details.

**Comment by giorgian** [comment]
Ops, this is already described in a comment here:
https://github.com/chef-cookbooks/database/commit/679aa0fdd42e6ebd5adbb57b243e549025cb28a6

**Comment by realPy** [comment]
Same problem for me.
Need to make depends < 5.0 to work

**Comment by isuftin** [comment]
I've been hit with the .empty? not being a Ruby thing (but is a Ruby on Rails) thing way too many times ;)

**Comment by tas50** [comment]
This should be fixed in the 5.0.1 release.

**Comment by sekrett** [comment]
Got this error on version 5.1.2. Because Mysql2::Result is not an array. You should use `size` instead of `empty?`, it was working before.

**Comment by sekrett** [comment]
Oh, rubocop gave you wrong directions, you've broken it here: https://github.com/chef-cookbooks/database/commit/7531f1b02eaef44f33ef6d3d5a0fee9bc943bf45
