### ISSUE TITLE
Sql guard interpreter

### ISSUE THREAD

**Issue by nwesoccer** [chef-cookbooks/database#203]
### Environment:

Microsoft 2012R2 with SQL Server 2014 Enterprise
### Scenario:

I'd like to conditionally execute a query only if another query returns a truthy value.
### Steps to Reproduce:

NA
### Expected Result:

It would be nice if there were a new guard interpreter for sql queries, just like there is for powershell.  You would pass your query to run and in the only_if or not_if you'd pass another query to check.
### Actual Result:

NA

I'm not sure if a GitHub Issue is the right place for this "request", if not, please direct me to the right location.  Thanks

**Comment by axos88** [comment]
+1

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
