### ISSUE TITLE
Add dependency to the mysql2_chef_gem cookbook

### ISSUE THREAD

**Issue by tpetchel** [chef-cookbooks/database#207]
We should consider having this cookbook depend on the `mysql2_chef_gem` cookbook to abstract that detail away from the user. This cookbook should install it for you if needed when you use any of the `database` resources that depend on the `mysql2` gem. Or we could add a default recipe to this cookbook that installs it, which would give users more control.

/cc @tas50

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
