### ISSUE TITLE
Error when granting :lock_tables permissions for Mariadb

### ISSUE THREAD

**Issue by rthideaway** [chef-cookbooks/database#211]
### Cookbook version

5.1.2
### Chef-client version

12.10.24
### Platform Details

Ubuntu 16.04 LTS Xenial
### Scenario:

Trying to add "lock tables" permission for mariadb user
### Steps to Reproduce:

mysql_database_user node['mariadb']['user'] do
  connection    mysql_connection_info
  password      node['mariadb']['password']
  database_name node['mariadb']['database']
  host          '127.0.0.1'
  privileges    [:select, :insert, :update, :delete, :create, :drop, :index, :alter, :lock_tables]
  action        :grant
end
### Expected Result:

Adding "lock tables" permission for an mariadb user
### Actual Result:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'lock_tables ON ...

User is not even able to import database dump, since it is containing plenty of locks on tables

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
