### ISSUE TITLE
Support GRANT for postgresql_database_user for objects other than DATABASE

### ISSUE THREAD

**Issue by iancward** [chef-cookbooks/database#215]
### Cookbook version

6.0.0
### Chef-client version

12.11
### Platform Details

RHEL6
### Scenario:

The postgresql_database_user resource expects a database to be specified (even though the README does state this requirement). I would like to be able to either not specify a database at all (grant privileges on all objects), or by to specify something other than a database (e.g. a specific table or view)
### Steps to Reproduce:

Call the resource without specifying a database or when specifying `pg_stat_database` (which is actually a view)
### Expected Result:

Grant is provided properly
### Actual Result:

```
ERROR: postgresql_database_user[datadog] (my_cookbook::datadog line 115) had an error: PG::SyntaxError: ERROR:  zero-length delimited identifier at or near """"
LINE 1: GRANT select ON DATABASE "" TO "datadog"
```

Here is the actual code: https://github.com/chef-cookbooks/database/blob/master/libraries/provider_database_postgresql_user.rb#L85

**Comment by tas50** [comment]
This should be done in 6.1.0
