### ISSUE TITLE
Mysql wont connect through network on Centos 6.7

### ISSUE THREAD

**Issue by chris-fa** [chef-cookbooks/database#216]
### Cookbook version

[Version of the cookbook where you are encountering the issue]
6.0
### Chef-client version

[Version of chef-client in your environment]
12.13.37
### Platform Details

[Operating system distribution and release version. Cloud provider if running in the cloud]
`bentos/centos-6.7`
### Scenario:

[What you are trying to achieve and you can't?]
Connect to mysql through network using `-h 127.0.0.1`
### Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
1. Create a database and a a database user with `'%'` host

``` ruby
mysql_database node['webserver']['database']['db_name'] do
  connection mysql_connection_info
  action :create
end

mysql_database_user node['webserver']['database']['admin_username'] do
  connection mysql_connection_info
  password node['webserver']['database']['admin_password']
  database_name node['webserver']['database']['db_name']
  host '%'
  action [:create, :grant]
end
```

Attempt to login through with host

``` bash
mysql -h 127.0.0.1 -u root -proot
```
### Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]
Connect to mysql successfully
### Actual Result:

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
It wont connect:

```
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (110)
```

**Comment by chris-fa** [comment]
it works perfectly on Centos 7.2, though.

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
