### ISSUE TITLE
Sql matchers do not follow naming pattern

### ISSUE THREAD

**Issue by eehaight** [chef-cookbooks/database#218]
### Cookbook version
6.0.0

### Chef-client version
12.13.37

### Platform Details
Windows 2012R2

### Scenario:
Running ChefSpec matcher against Sql Server resource with query matcher always fails. In the libraries/matchers.rb file, the SQL matcher is named query_database. This is a duplicate matcher. This should be named quer_sql_server_database to be consistent with the rest of the matchers.

**Comment by tas50** [comment]
I've fixed this in master. I'll get a release shortly
