### ISSUE TITLE
Can't edit database remotely

### ISSUE THREAD

**Issue by tobymaro** [chef-cookbooks/database#222]
### Cookbook version
5.1.2

### Chef-client version
Chef: 12.7.2

### Platform Details
CentOS Linux release 7.2.1511 (Core)

### Scenario:
I'm testing my environment. Actually I will have 2 nodes. First - DB, Second - Gerrit. But for testing I install both roles on one node.  I installed postgresql using your cookbook.  

```
#Init connection creds
postgresql_connection_info = {
  :host =>  '127.0.0.1',
  :port =>  node['postgresql']['config']['port'],
  :username => "postgres",
  :password => node['postgresql']['password']['postgres']
}

#Create db user for gerrit
postgresql_database_user node['gerrit']['database']['username'] do
  connection postgresql_connection_info
  password db_password
  action :create
end

#Create db for gerrit
postgresql_database node['gerrit']['database']['database'] do
  connection postgresql_connection_info
  owner node['gerrit']['database']['username']
  action :create
end

#Grant privileges for gerrit db user
postgresql_database_user node['gerrit']['database']['username'] do
  connection postgresql_connection_info
  database_name node['gerrit']['database']['database']
  privileges [
    :all
  ]
  action :grant
end

```
### Steps to Reproduce:

Added to pg_hba.conf line 

# Allow access for gerrit user
host    reviewdb        gerrit          0.0.0.0/0               md5

And now I trying to modify database with code

```
postgresql_connection_info = {
    :host =>  node['gerrit']['database']['hostname'],     #(return DB nodes IP)
    #:host =>  '127.0.0.1',                                        
    :port =>  node['postgresql']['config']['port'],
    :username => node['gerrit']['database']['username'],  # gerrit
    :password => data_bag_item('gerrit_mysql', 'creds')['db_password'] #password
  }
```
All attributes exist. It's 100%.

postgresql_database 'Additional configuration script' do
    connection postgresql_connection_info
    sql { ::File.open(init_sql).read }
    database_name node['gerrit']['database']['database']  #reviewdb
    action :query
  end

Script is pretty simple and insert only one row to table. 

### Expected Result:
gerrit node connects to db nodes to database reviewdb (instead of template1) and create needed records

### Actual Result:

But I got this message from chef-client

 ================================================================================
    Error executing action `query` on resource 'postgresql_database[Additional configuration script]'
    ================================================================================

    PG::ConnectionBad
    -----------------
    FATAL:  no pg_hba.conf entry for host "10.244.129.154", user "gerrit", database "template1", SSL off

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `initialize'
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `new'
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:132:in `db'
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:97:in `exists?'
    /var/chef/cache/cookbooks/database/libraries/provider_database_postgresql.rb:80:in `block in <class:Postgresql>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/gerrit/recipes/default.rb

    121:   postgresql_database 'Additional configuration script' do
    122:     connection postgresql_connection_info
    123:     sql { ::File.open(init_sql).read }
    124:     database_name node['gerrit']['database']['database']
    125:     action :query
    126:   end
    127: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/gerrit/recipes/default.rb:121:in `from_file'

    postgresql_database("Additional configuration script") do
      provider Chef::Provider::Database::Postgresql
      action [:query]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      database_name "reviewdb"
      declared_type :postgresql_database
      cookbook_name "gerrit"
      recipe_name "default"
      connection {:host=>"CDC.home.com", :port=>5432, :username=>"gerrit", :password=>"????????"}
      sql #<Proc:0x00000008576d10@/var/chef/cache/cookbooks/gerrit/recipes/default.rb:123>
    end

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
