### ISSUE TITLE
Set root password for connecting via socket

### ISSUE THREAD

**Issue by mastermindg** [chef-cookbooks/database#224]
### Cookbook version
6.1.1

### Chef-client version
12.17.44

### Platform Details
Centos 7 - Virtualbox - Vagrant

### Scenario:
I install MySQL via yum-mysql-community. Initially there is no root password set.

### Steps to Reproduce:
 -- include_recipe 'yum-mysql-community::mysql56'
 -- package install mysql-community-server
 -- service start/enable mysqld
 -- mysql2_chef_gem install
 -- mysql_database create database
 -- mysql_database_user root set permissions for new database with password
 -- mysql_database_user root set permissions for 'mysql' database with password

### Expected Result:
Local user logged in to the server should have to enter a password when connecting to mysql:
```mysql -u root -p```
```ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)```

### Actual Result:
Local user logged in to the server does not have to enter a password when connecting to mysql:
```mysql -u root```
```mysql>```

Is there any way to set/require the password for connecting locally via the socket?

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
