### ISSUE TITLE
Do not display password in output from chef-client on error

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/database#71]
Working with the mysql_database_user resource, a failed connection to the database will result in the password being displayed in plain text in the output from chef client.  For example, the following is spit out from a failed chef-client run.

```
mysql_database_user("create-db-user") do
  provider Chef::Provider::Database::MysqlUser
  action [:grant]
  retries 0
  retry_delay 2
  guard_interpreter :default
  database_name "mydb"
  username "myuser"
  host "10.%"
  privileges [:select, :delete, :update, :insert]
  cookbook_name "mycookbook"
  recipe_name "myrecipe"
  connection {:host=>"10.0.0.1", :username=>"root", :password=>"my_root_password_displayed_in_plain_text"}
  password "my_new_user_password_in_plain_text"
end
```

This is obviously a security hole that should be fixed.

**Comment by philosowaffle** [comment]
+1

**Comment by evaryont** [comment]
Is there a way to force `sensitive true` in an LWRP? That would be the best solution, I think.

In the mean time, you can add it to all of your uses for mysql_database_user. Though this precaution is still defeated until #93 is solved, or #138 is merged.

**Comment by gravesb** [comment]
That documentation is wrong.  The sensitive attribute was added to the base resource object back in 11.14.0.  See https://github.com/chef/chef/commit/cee94f52d52806885fbd63d63addc3708b25f409

**Comment by evaryont** [comment]
Glad to hear it. It would be even better if the LWRP could somehow enable that to be true. And thankfully, #138 has been merged so this is the only remaining password log, that I can tell.

Does this affect other LWRPs? PostgreSQL, for instance?

**Comment by gravesb** [comment]
As long as they're not doing any additional custom logging within the lwrp, then yes the sensitive flag should apply and the resource logging performed automatically by chef upon an exception should suppress any sensitive resource details.

**Comment by ovaistariq** [comment]
Unfortunately sensitive flag does not really work even though its being passed on to the Chef::Resource base class. See #162 for details.

**Comment by ozzyogkush** [comment]
Agree this is needed. Even at log level info it will output a password when using the grant action.

**Comment by tas50** [comment]
At this time I'm going to close this issue out as we've deprecated this cookbook. The original intent was to abstract database implementation details away from the end user. In hindsight this was a mistake as it is difficult / impossible to make a generic interface for databases that works across all systems. Instead we plan to move the individual providers into their respective cookbooks (mysql, postgresql, sqlite, sql_server) where they can fully utilize the feature set of the underlying DB systems.
