### ISSUE TITLE
query action examples for postgresql are incorrect.

### ISSUE THREAD

**Issue by bkett** [chef-cookbooks/database#87]
A query action will not run unless you specify which postgres database to run the query against. Going to submit a PR with updates to those examples.

**Comment by iennae** [comment]
@bkett Thanks for opening up this issue. As it's been a while, I'm not sure if this has been resolved or not, or if the PR that you had mentioned submitting has already been merged or never completed. I also understand this might not be an issue that you care about at this time. I'm going to go ahead and close this issue. If it's still a problem and you want to help us resolve it, please feel free to reopen this with additional information. Thanks!
