### ISSUE TITLE
Postgres permissions for a database user

### ISSUE THREAD

**Issue by gdavison** [chef-cookbooks/database#94]
I'm not an expert in Postgres configuration, so maybe there's something obvious that I'm missing, but I can't give a new database user permissions on tables in a database. The default recipe gives the user `CONNECT` privileges to a database, but tables can't be accessed.

Here's what I started with:

``` ruby
postgresql_connection_info = {
  :host     => 'localhost',
  :port     => 5432,
  :username => 'postgres',
  :password => 'password'
}
postgresql_database 'foo' do
  connection postgresql_connection_info
  action     :create
end
postgresql_database_user 'foo_user' do
  password      'foo_user_password'
  connection    postgresql_connection_info
  action        :create
end
postgresql_database_user "grant permissions to foo_user" do
  connection    postgresql_connection_info
  username      'foo_user'
  database_name 'foo'
  action        :grant
  privileges    [:all]
end
```

The last step, "grant permissions to foo_user", does not actually appear to do anything.

I've also tried

``` ruby
postgresql_database "grant permissions to foo_user" do
  connection    postgresql_connection_info
  database_name'foo'
  action        :query
  sql           "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO foo_user"
end
```

which doesn't do anything. If I run the command directly in `psql`, it does work.

**Comment by diegows** [comment]
Same problem here!

**Comment by rschwiebert** [comment]
I have a coworker trying to create a user that can insert rows into tables, but can't get the permissions granted through the recipe.

**Comment by rschwiebert** [comment]
@gdavison In all cases I've seen, the username goes after "postgres_database_user", so are you sure that where you try to do grants with  
```postgresql_database_user "grant permissions to foo_user" do```

it shouldn't be 
```postgresql_database_user "foo_user" do``` 

instead?  (Yes, I realize you filled out the username attribute, and I don't know if that takes precedent.)

**Comment by gdavison** [comment]
@rschwiebert I think the problem here is that I already have a resource `postgresql_database_user 'foo_user'` which creates the user. Each resource needs to have a distinct name, and the `username` attribute does take precedence.
Perhaps there should be different resources for creating a user and assigning permissions.

**Comment by tas50** [comment]
I believe our improved grant functionality in 6.1.0 fixes part of this, but also you need to have unique names to avoid merging the resources together. I'm going to close this out now. Feel free to open it back up with additional information if you have insight into the issue with 6.1.0+
